name: quick_stock
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.10+10

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.3.4
  intl: ^0.18.1
  uuid: ^3.0.7
  shared_preferences: ^2.2.0
  connectivity_plus: ^6.1.0
  share_plus: ^7.2.1
  pdf: ^3.10.7
  flutter_pdfview: ^1.3.2
  permission_handler: ^11.0.1
  file_picker: ^6.1.1
  path_provider: ^2.1.2
  open_file: ^3.3.2
  url_launcher: ^6.2.1
  path: ^1.8.3
  app_settings: ^5.1.1
  package_info_plus: ^8.1.1
  flutter_markdown: ^0.6.18
  printing: ^5.11.1
  google_fonts: ^6.1.0
  qr: ^3.0.1
  barcode: ^2.2.4
  fl_chart: ^0.65.0
  excel: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
